apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.4
    helm:
      releaseName: ingress-nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true # enable automatic sync when the live cluster's state deviates from the state defined in Git
      prune: true # prune any changes that differ from git repo
